name: test matrix flow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: 'Environment to run tests against'
        required: true
        type: environment
jobs:
  my_matrix_example:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [10]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - os: ubuntu-latest
            version: 10
    steps: 
     - name: Print env
       id: print-env
       run: echo "testing ${{inputs.environment}}"
     - id: print-matrix
       run: |
         echo "Matrix info: ${{ matrix.version }} and ${{ matrix.os }}"
   #  - if: ${{ matrix.version == '10'  &&  matrix.os == 'windows-latest' }}
   #    run: |
   #    echo "::error::testing error message"
   #    exit -1
     - if: ${{ vars.MY_VAR != '' }}
       run: |
         echo "WORKFLOW_VAR=${{ vars.MY_VAR }}" >> $GITHUB_ENV

     - if: ${{ vars.MY_VAR == '' }}
       run: |
           echo "WORKFLOW_VAR=I-do-not-have-my-var" >> $GITHUB_ENV

     - run: echo $WORKFLOW_VAR
     

    
